const sentences = {
  easy: [
    'The cat sits on the mat.',
    'I like to eat pizza.',
    'She runs very fast.',
    'We play in the park.',
    'The sun is bright today.',
    'Birds fly in the sky.',
    'Water is very cold.',
    'My dog likes to bark.',
    'Books are on the shelf.',
    'Time flies so fast.',
    'He drinks a cup of tea.',
    'They walk to the bus stop.',
    'I write notes every day.',
    'The room is very quiet.',
    'Close the door before you go.',
    'Open the window for fresh air.',
    'Keep your hands on the home row.',
    'Type slowly and stay calm.',
    'Rain falls softly tonight.',
    'Please pass me the salt.'
  ],
  medium: [
    'Technology has changed our lives completely.',
    'Learning new skills requires dedication and practice.',
    'The ocean waves crashed against the rocky shore.',
    'Musicians create beautiful melodies that touch hearts.',
    'Scientists discover new things every single day.',
    'Traveling opens your mind to different cultures.',
    'Reading books expands your imagination greatly.',
    'Exercise keeps your body healthy and strong.',
    'Cooking delicious meals brings people together happily.',
    'Nature provides us with amazing beautiful scenery.',
    'Daily routines help build consistent habits over time.',
    'Typing accuracy improves when you relax your shoulders.',
    'Short breaks prevent fatigue during long sessions.',
    'Set realistic goals and track your progress weekly.',
    'Practice makes permanent, so focus on good form.',
    'Use all fingers to reduce strain and increase speed.',
    'A clean workspace can boost your concentration.',
    'Listening to calm music may help you focus.',
    'Reflecting on mistakes turns them into lessons.',
    'Consistency beats intensity in the long run.'
  ],
  hard: [
    'The extraordinary phenomenon captivated researchers worldwide.',
    'Philosophical discussions often lead to profound realizations.',
    'Unprecedented technological advancements revolutionize industries continuously.',
    'Environmental conservation requires immediate collaborative action globally.',
    'Psychological research demonstrates fascinating behavioral patterns consistently.',
    'Archaeological discoveries reveal ancient civilizations mysterious secrets.',
    'Mathematical equations describe universal natural phenomena precisely.',
    'Entrepreneurial ventures demand creativity, persistence, and strategic thinking.',
    'Artificial intelligence transforms computational capabilities exponentially faster.',
    'Interdisciplinary collaboration produces innovative solutions for complex problems.',
    'Meticulous attention to detail significantly reduces systematic errors.',
    'Sustainable development balances economic growth with ecological integrity.',
    'Cognitive load management enhances learning efficiency and retention.',
    'Decentralized systems mitigate single points of failure effectively.',
    'Empirical evidence must guide policy decisions to remain credible.',
    'Cross-functional teams accelerate delivery in uncertain environments.',
    'Ethical frameworks constrain the misuse of powerful technologies.',
    'Longitudinal studies illuminate trends invisible in cross-sectional data.',
    'Adaptive strategies thrive under volatile, uncertain, complex conditions.',
    'Robust feedback loops are essential for continuous improvement.'
  ]
};

export default sentences;
