name = "portfolio-worker"
main = "src/index.ts"
compatibility_date = "2026-04-07"
compatibility_flags = ["nodejs_compat"]

routes = [
   { pattern = "portfolio-worker.onurd.com.tr", zone_name = "onurd.com.tr" },
]

account_id = "df78ac02dad5500795c67541353ed776"

[vars]
FRONTEND_URL = "https://onurd.com.tr"
RESEND_FROM = "Onur Dursun <admin@onurd.com.tr>"
JWT_SECRET = "onur_portfolio_jwt_secure_secret_key_2026_999"
REFRESH_TOKEN_SECRET = "onur_portfolio_refresh_secure_secret_key_2026_999"
JWT_EXPIRATION_TIME = "7d"
REFRESH_TOKEN_EXPIRATION_TIME = "30d"

[ai]
binding = "AI"
